### Inscription par téléphone
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "nom": "Kamga",
  "prenom": "Paul",
  "telephone": "690123456",
  "password": "monpass123"
}

### Inscription par email
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "nom": "Dupont",
  "prenom": "Marie",
  "email": "marie@gmail.com",
  "password": "123456"
}

### Connexion par téléphone
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "telephone": "690123456",
  "password": "monpass123"
}

### Connexion par email
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "marie@gmail.com",
  "password": "123456"
}

### 3. Accès route protégée → colle le token ici
### Accès à la route protégée
GET http://localhost:8080/api/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzb3BoaWUubWFydGluQGdtYWlsLmNvbSIsImlhdCI6MTc2MzQ1MTA0NSwiZXhwIjoxNzYzNDU0NjQ1fQ.C9eP8NP0FeGuN35MmJgWGmzNIDBL55CitnY3mRc5nDQ